# fly.toml app configuration file generated for initiatetodoapp-nameless-sound-771-empty-butterfly-8790-fragrant-hill-1100-blue-violet-9889 on 2024-03-17T16:22:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'initiatetodoapp-nameless-sound-771-empty-butterfly-8790-fragrant-hill-1100-blue-violet-9889'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
